[Info]
name = "A runner shell spec"
description = """
An ogc spec showing out the runner and runner-shell plugin works
"""

[Env]
requires = ["HOME"]

[[Runner]]
name = "Showing env.properties"
run = """
#!/bin/bash
set -eux

cat fixtures/env.properties
"""

[[Runner]]
name = "A script cleanup"
run_script = "fixtures/env-cleanup"
executable = "python3"